---
install:
  - set QTDIR=C:\Qt\5.13\mingw73_64
  - set MINGWDIR=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64
  - set PATH=%PATH%;%QTDIR%\bin;%MINGWDIR%\bin;C:\Qt\QtIFW-3.1.1\bin
before_build:
  - qmake emtv.pro
build_script:
  ps: |
    dir C:\
    dir C:\MinGW
    dir C:\mingw-w64
    dir c:\msys64
    dir C:\Qt\5.13\mingw73_64
    dir C:\Qt\Tools\mingw730_64
    dir C:\Qt
    dir C:\Qt\5.13
    dir C:\Qt\Tools
    dir C:\Qt\Tools\QtInstallerFramework
    dir
    mingw32-make
    mkdir emtv
    cp release\emtv.exe emtv\
    cd emtv
    windeployqt.exe emtv.exe
    cd ..
    7z a emtv-win.7z emtv\
    mkdir win-install\packages\com.github.cmosher01.emtv\data
    mv emtv-win.7z win-install\packages\com.github.cmosher01.emtv\data\
    cd win-install
    binarycreator.exe --offline-only -c config\config.xml -p packages setup-emtv.exe
    mv win-install\setup-emtv.exe .\
artifacts:
  - name: zipfile
    path: setup-emtv.exe
deploy:
  description: Latest stable release
  provider: GitHub
  auth_token:
    secure: TjyyWBvqvk2/j05cBmpMpWsBslEdpJV2JOWy/5Uwr7IP1zKVMx/x97deqVskxx6L
  artifact: zipfile
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
