---
install:
  - set QTDIR=C:\Qt\5.13\mingw73_64
  - set QTIFWDIR=C:\Qt\Tools\QtInstallerFramework\3.1
  - set MINGWDIR=C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64
  - set PATH=%PATH%;%QTDIR%\bin;%MINGWDIR%\bin;%QTIFWDIR%\bin
before_build:
  - qmake emtv.pro
build_script:
  ps: |
    echo "Some interesting directories"
    dir C:\
    dir C:\MinGW\bin
    dir C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin
    dir c:\msys64
    dir C:\Qt\5.13\mingw73_64\bin
    dir C:\Qt\Tools\mingw730_64\bin
    dir C:\Qt
    dir C:\Qt\5.13\mingw73_64\bin
    dir C:\Qt\Tools
    dir C:\Qt\Tools\mingw730_64
    dir C:\Qt\Tools\QtInstallerFramework
    dir C:\Qt\Tools\QtInstallerFramework\3.1\bin
    dir
    echo "BUILD"
    mingw32-make
    echo "GATHER DEPENDENCIES"
    mkdir emtv
    cp release\emtv.exe emtv\
    cd emtv
    windeployqt.exe emtv.exe
    cd ..
    echo "ZIP PACKAGE"
    7z a emtv-win.7z emtv\
    mkdir win-install\packages\com.github.cmosher01.emtv\data
    mv emtv-win.7z win-install\packages\com.github.cmosher01.emtv\data\
    echo "CREATE INSTALLER SETUP.EXE"
    cd win-install
    binarycreator.exe --offline-only -c config\config.xml -p packages emtv-win-setup.exe
    cd ..
    mv win-install\emtv-win-setup.exe .\
artifacts:
  - name: setupexe
    path: emtv-win-setup.exe
deploy:
  description: Latest stable release
  provider: GitHub
  auth_token:
    secure: TjyyWBvqvk2/j05cBmpMpWsBslEdpJV2JOWy/5Uwr7IP1zKVMx/x97deqVskxx6L
  artifact: setupexe
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
