language: cpp

env:
  global:
    - NAME=emtv

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      before_install:
        - sudo apt-get -qq update
      install:
        - sudo apt-get install -y build-essential qt5-default
      script:
        - qmake
        - make
        - zip -j ${NAME}-${TRAVIS_OS_NAME} $(basename *.pro .pro)
    - os: osx
      env:
        - PATH=/usr/local/opt/qt/bin:$PATH
      install:
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install qt
      script:
        - qmake
        - make
        - zip -j ${NAME}-${TRAVIS_OS_NAME} ${NAME}.app/Contents/MacOS/${NAME}

deploy:
  provider: releases
  api_key:
    secure: VnB/f99CFbZtXLYQ4zEb8oirto3mkOoxMzrGkc0ia7p0jhAPLz40TyxOcilseuIUgh+9GrIP18PaMMn0+2imgQ2Z6+YE8wdBt2QIkJ1uJWZuDY/3ZXCMBTM4aRQMdtdewx6+tCPaqTiPm5a9NbqVhIh9/fuhl7q4LiOl+vzmK/qOexMaH8EAuFcWyxA5GiZg4ktADa6+h7GMv8bDKu+wPVPTcR5/sPlcnqmjxhnL1zJcpRnLT9Yx6zP12+hEG7Uy3/7Zlmk1/v48H7r6tNzXNYcnjrWrwXHf4vQaH5Vg8VEWxTH7ENYZrxzKPDg1jLWi4sSKXUkEXVtKjIeWKPoCJvwMolv3pA6Eou4n6W0YLuxzGNmXSBpxxIaQtc3xisE9CFmGrbtlfXtOASGmbREjLFGjVrPf3YCWFnutjMyQ0kxWis4dzIVCIbgC3t59yoEp2ziJJuxccgnbhJ1LlsLB2tgM6nkdyI8JbnDZfLA3Zm0ATCCaTHn2NQHkuEebnWTP6i3hftSBgKUZ/d2d7hDeXYt0jXG+WlwtaQWOYoHWA/M6naw5LSL4ygj3xMSalVVZHt7CCSdogLMm0haBIbpUSIkwsMwzrzxvUnMu3gzgLSgFIDLqeYRga3IqcvhVJH1wtFh4/tYvovFFfbNXu5SF59tAc7hHCWfo2Bmsw+HO/T4=
  file_glob: true
  file: "*.zip"
  on:
    tags: true
