---
on:
  push:
    # tags:
    #   - "*"
    branches:
      - "master"

jobs:
  "publish":
    strategy:
      matrix:
        os:
          # - "ubuntu-latest"
          - "windows-latest"
          # - "macos-latest"

    runs-on: "${{ matrix.os }}"

    permissions:
      contents: "write"

    steps:
      - uses: "actions/checkout@v3"

      - uses: "msys2/setup-msys2@v2"
        with:
          msystem: "mingw64"
          release: false

      - uses: "jurplel/install-qt-action@v3"

      # - uses: "egor-tensin/vs-shell@v2"

      - run: "qmake"
        shell: "msys2 {0}"

      - run: "make"
        shell: "msys2 {0}"

      - run: "ls"
        shell: "msys2 {0}"
