---
on:
  push:
    tags:
      - "*"

env:
  name: "emtv"

jobs:
  "publish":
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"

    runs-on: "${{ matrix.os }}"

    permissions:
      contents: "write"

    steps:
      - uses: "actions/checkout@v3"

      - uses: "egor-tensin/vs-shell@v2"

      - uses: "jurplel/install-qt-action@v3"

      - run: "qmake"

      - run: "make"
        if: "${{ matrix.os == 'ubuntu-latest'}}"
      - run: |
          make
          macdeployqt $name.app
        if: "${{ matrix.os == 'macos-latest'}}"
      - run: "nmake"
        if: "${{ matrix.os == 'windows-latest'}}"



      # - run: "ls -l"
      #   if: "${{ matrix.os == 'ubuntu-latest'}}"
      # - run: "ls -lR"
      #   if: "${{ matrix.os == 'macos-latest'}}"
      # - run: "Get-ChildItem -Recurse"
      #   if: "${{ matrix.os == 'windows-latest'}}"



      - run: "pkgbuild --install-location /Applications --identifier nu.mine.mosher.$name --component $name.app/ $name.pkg"
        if: "${{ matrix.os == 'macos-latest'}}"

      # - uses: "softprops/action-gh-release@v1"
      #   if: "${{ matrix.os == 'ubuntu-latest'}}"
      #   with:
      #     files: "${{ env.name }}"
      - uses: "softprops/action-gh-release@v1"
        if: "${{ matrix.os == 'macos-latest'}}"
        with:
          files: "${{ env.name }}.pkg"
      # - uses: "softprops/action-gh-release@v1"
      #   if: "${{ matrix.os == 'windows-latest'}}"
      #   with:
      #     files: "release/${{ env.name }}.exe"
