---
on:
  push:
    # tags:
    #   - "*"
    branches:
      - "master"

jobs:
  "publish":
    strategy:
      matrix:
        os:
          # - "ubuntu-latest"
          - "windows-latest"
          # - "macos-latest"

    runs-on: "${{ matrix.os }}"

    permissions:
      contents: "write"

    steps:
      - uses: "actions/checkout@v3"

      - uses: "jurplel/install-qt-action@v3"

      - run: "qmake"

      - run: "nmake"

      - run: "ls"
