---
on:
  push:
    tags:
      - "*"

env:
  name: "emtv"
  desc: "Black and white NTSC TV emulator"
  deb_depends: "libqt5core5a, libqt5gui5, libqt5widgets5"

permissions:
  contents: "write"





jobs:
  "publish-ubuntu":
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"

      - run: |
          set -x
          sudo apt-get install --quiet --verbose-versions --yes qtbase5-dev qt5-qmake
          qmake
          make
          mkdir -p ./deb/usr/bin/
          cp ${{ env.name }} ./deb/usr/bin/

      - uses: "jiro4989/build-deb-action@v2"
        with:
          package: "${{ env.name }}"
          desc: "${{ env.desc }}"
          maintainer: "${{ github.repository_owner }}"
          version: "${{ github.ref }}"
          arch: "amd64"
          package_root: "./deb/"
          depends: "${{ env.deb_depends }}"

      - uses: "softprops/action-gh-release@v1"
        with:
          files: |
            *.deb





  "publish-macos":
    runs-on: "macos-latest"
    steps:
      - uses: "actions/checkout@v3"

      - uses: "jurplel/install-qt-action@v3"
        with:
          version: "5.15.2"

      - run: |
          set -x
          qmake
          make
          macdeployqt $name.app
          pkgbuild --install-location /Applications --identifier nu.mine.mosher.$name --component $name.app/ $name.pkg

      - uses: "softprops/action-gh-release@v1"
        with:
          files: |
            *.pkg





  "publish-windows":
    runs-on: "windows-latest"
    steps:
      - uses: "actions/checkout@v3"

      - uses: "egor-tensin/vs-shell@v2"

      - uses: "jurplel/install-qt-action@v3"
        with:
          version: "5.15.2"

      - run: |
          qmake
          nmake
          Rename-Item -Path "release" -NewName "${{ env.name }}"
          windeployqt ${{ env.name }}/${{ env.name }}.exe
          Copy-Item "AppxManifest.xml" -Destination "${{ env.name }}"
          Copy-Item "small.png" -Destination "${{ env.name }}"
          MakeAppx pack /v /h SHA384 /d ${{ env.name }} /p ${{ env.name }}-windows.msix

      - uses: "thedoctor0/zip-release@main"
        with:
          path: "${{ env.name }}"
          filename: "${{ env.name }}-windows.zip"

      - uses: "softprops/action-gh-release@v1"
        with:
          files: |
            *.zip
            *.msix
