---
on:
  push:
    tags:
      - "*"

env:
  name: "emtv"
  desc: "Black and white NTSC TV emulator"
  deb_depends: "libqt5core5a, libqt5gui5, libqt5widgets5"

jobs:
  "publish":
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"

    runs-on: "${{ matrix.os }}"

    permissions:
      contents: "write"

    steps:
      - uses: "actions/checkout@v3"

      - uses: "egor-tensin/vs-shell@v2"
        if: "${{ matrix.os == 'windows-latest'}}"

      - uses: "jurplel/install-qt-action@v3"
        with:
          version: "6.4.0"

      - run: "qmake"



      - run: |
          make
          mkdir -p ./deb/usr/bin/
          cp ${{ env.name }} ./deb/usr/bin/
          mkdir -p ./rpm/usr/bin/
          cp ${{ env.name }} ./rpm/usr/bin/
        if: "${{ matrix.os == 'ubuntu-latest'}}"
      - uses: "jiro4989/build-deb-action@v2"
        if: "${{ matrix.os == 'ubuntu-latest'}}"
        with:
          package: "${{ env.name }}"
          desc: "${{ env.desc }}"
          maintainer: "${{ github.repository_owner }}"
          version: "${{ github.ref }}"
          arch: "amd64"
          package_root: "./deb/"
          depends: "${{ env.deb_depends }}"
      # - uses: "jiro4989/build-rpm-action@v2"
      #   if: "${{ matrix.os == 'ubuntu-latest'}}"
      #   with:
      #     package: "${{ env.name }}"
      #     summary: "${{ env.desc }}"
      #     maintainer: "${{ github.repository_owner }}"
      #     version: "${{ github.ref }}"
      #     arch: "x86_64"
      #     package_root: "./rpm/"
      #     requires: "${{ env.rpm_depends }}" # NOT IMPLEMENTED
      - uses: "softprops/action-gh-release@v1"
        if: "${{ matrix.os == 'ubuntu-latest'}}"
        with:
          files: |
            *.deb



      - run: |
          nmake
          Rename-Item -Path "release" -NewName "${{ env.name }}"
          windeployqt ${{ env.name }}/${{ env.name }}.exe
          Copy-Item "AppxManifest.xml" -Destination "${{ env.name }}"
          Copy-Item "small.png" -Destination "${{ env.name }}"
          Get-ChildItem -Recurse
          MakeAppx pack /v /h SHA384 /d ${{ env.name }} /p ${{ env.name }}.msix
        if: "${{ matrix.os == 'windows-latest'}}"

      - uses: "thedoctor0/zip-release@main"
        if: "${{ matrix.os == 'windows-latest'}}"
        with:
          path: "${{ env.name }}"
          filename: "${{ env.name }}-win.zip"

      - uses: "softprops/action-gh-release@v1"
        if: "${{ matrix.os == 'windows-latest'}}"
        with:
          files: "${{ env.name }}-win.zip"
          # don't release .msix because it's not signed



      - run: |
          make
          macdeployqt $name.app
          pkgbuild --install-location /Applications --identifier nu.mine.mosher.$name --component $name.app/ $name.pkg
        if: "${{ matrix.os == 'macos-latest'}}"

      - uses: "softprops/action-gh-release@v1"
        if: "${{ matrix.os == 'macos-latest'}}"
        with:
          files: "${{ env.name }}.pkg"
