---
on:
  push:
    # tags:
    #   - "*"
    branches:
      - "master"

env:
  name: "emtv"

jobs:
  "publish":
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"

    runs-on: "${{ matrix.os }}"

    permissions:
      contents: "write"

    steps:
      - uses: "actions/checkout@v3"

      - uses: "egor-tensin/vs-shell@v2"

      - uses: "jurplel/install-qt-action@v3"

      - run: "qmake"

      - run: "make"
        if: "${{ matrix.os == 'ubuntu-latest'}}"
      - run: "make"
        if: "${{ matrix.os == 'macos-latest'}}"
      - run: "nmake"
        if: "${{ matrix.os == 'windows-latest'}}"

      - run: "ls -l $name"
        if: "${{ matrix.os == 'ubuntu-latest'}}"
      - run: "ls -lR $name.app"
        if: "${{ matrix.os == 'macos-latest'}}"
      - run: "ls release/$Env:name"
        if: "${{ matrix.os == 'windows-latest'}}"

      - run: "pkgbuild --identifier nu.mine.mosher.$name --root $name.app $name.pkg"
        if: "${{ matrix.os == 'macos-latest'}}"
      - run: "ls -l"
        if: "${{ matrix.os == 'macos-latest'}}"

      - uses: "softprops/action-gh-release@v1"
        if: "${{ matrix.os == 'ubuntu-latest'}}"
        with:
          files: "$name"
      - uses: "softprops/action-gh-release@v1"
        if: "${{ matrix.os == 'macos-latest'}}"
        with:
          files: "$name.pkg"
      - uses: "softprops/action-gh-release@v1"
        if: "${{ matrix.os == 'windows-latest'}}"
        with:
          files: "release/$Env:name.exe"
