---
on:
  push:
    # tags:
    #   - "*"
    branches:
      - "master"

jobs:
  "publish":
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"

    runs-on: "${{ matrix.os }}"

    permissions:
      contents: "write"

    steps:
      - uses: "actions/checkout@v3"

      - uses: "egor-tensin/vs-shell@v2"

      - uses: "jurplel/install-qt-action@v3"

      - run: "qmake"

      - run: "nmake"
        if: "${{ matrix.os == 'windows-latest'}}"
      - run: "make"
        if: "${{ matrix.os == 'macos-latest'}}"
      - run: "make"
        if: "${{ matrix.os == 'ubuntu-latest'}}"

      - run: "ls release"
